<!--Starts Footer.inc-->
<style>
    footer {
    font-family: Arial, Helvetica, sans-serif;
    font-weight: normal;
    font-size: small;
    padding: 0;
    margin: 0;
    width: 100%;
    text-align: center;
    display: block;
    word-break: keep-all;
}
</style>
<footer>
    <div id="footer" class="clearing">
        <p>Copyright &copy; <a href="http://www.kpiguy.net">Marshall Berg</a> 2015 | Contact <a
                href="mailto:marshall@speedyscstores.com?subject=MS3SupportRequest">e-mail
                WebAdmin</a> | Phone:<a type="tel">
                (816) 550-2385</a> </p>
    </div>
</footer>
</body>
</html>