
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="Marshall Berg">
    <meta name="description" content="Internal Processes Management System">
    <meta name="keywords" content="Input Forms, Documents, Training">
    <title><?php echo $heading;?></title>
</head>
<link rel="stylesheet" type="text/css" href="scripts/main.css">
<script src="scripts/jquery-2.1.3.min.js"></script>
<script src="scripts/tz.js"></script>
<style>
    body {
        font-family: Arial, Helvetica, sans-serif;
        font-weight: bold;
        font-size: 1.5em;
        padding: 0;
        width: 100%;
    }
    header div{
        margin: top: 0;
        display: block;
        background-color: black;
        color: darkgreen;
        text-align: center;
    }
</style>
<body>
<header>
    <div>
        <h1><?php echo " " . $heading;?></h1>
    </div>
</header>

<!--Ends Header.inc-->